# Generated by Django 4.1 on 2022-10-16 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Product Name')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Date')),
                ('sellingPrice', models.IntegerField(verbose_name='Selling Price')),
                ('factory', models.CharField(max_length=30, verbose_name='Factory name')),
            ],
            options={
                'verbose_name': 'Invoice History',
                'verbose_name_plural': 'Invoices History',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Code')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('category', models.CharField(blank=True, max_length=50, null=True, verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Number')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('customer', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer')),
                ('customerName', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Name')),
                ('address', models.CharField(blank=True, max_length=30, null=True, verbose_name='Address')),
                ('documentSeries', models.CharField(blank=True, max_length=10, null=True, verbose_name='Document Series')),
                ('bankDetails', models.CharField(blank=True, max_length=20, null=True, verbose_name='Bank Details')),
                ('sellingPrice', models.IntegerField(blank=True, null=True, verbose_name='Selling Price')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='Country')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Date')),
                ('count', models.CharField(blank=True, max_length=10, null=True, verbose_name='Count')),
                ('factory', models.CharField(blank=True, max_length=30, null=True, verbose_name='Factory Name')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
