# Generated by Django 4.1 on 2022-10-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_invoice_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicehistory',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.invoice'),
        ),
    ]
