# Generated by Django 4.1.2 on 2022-10-28 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_invoicehistory_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='Healthy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discription', models.CharField(blank=True, max_length=50, null=True, verbose_name='Discription')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'Healthy',
                'verbose_name_plural': 'Healthy',
            },
        ),
        migrations.CreateModel(
            name='MedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Name')),
                ('diagnos', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diagnos')),
                ('cause', models.CharField(blank=True, max_length=50, null=True, verbose_name='Cause')),
                ('other', models.CharField(blank=True, max_length=50, null=True, verbose_name='Other')),
                ('gender', models.CharField(blank=True, max_length=1, null=True, verbose_name='Gender')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Date')),
            ],
            options={
                'verbose_name': 'MedCard',
                'verbose_name_plural': 'MedCards',
            },
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, default='', null=True, verbose_name='Date')),
                ('medCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medcard')),
            ],
            options={
                'verbose_name': 'Move',
                'verbose_name_plural': 'Move',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
            },
        ),
        migrations.RemoveField(
            model_name='invoicehistory',
            name='invoice',
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
        migrations.DeleteModel(
            name='InvoiceHistory',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.AddField(
            model_name='move',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.room'),
        ),
        migrations.AddField(
            model_name='healthy',
            name='medCard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.medcard'),
        ),
    ]
